Feature/experience/husbandry
Ixsen/Mastery pull request #17
Opened 2018-08-10 20:24 UTC by Ixsen

2018-08-10 21:23 UTC, jsprey requested changes

2018-08-10 21:23 UTC, jsprey commented on src/main/java/mastery/capability/skillclasses/CombatMastery.java
> -    public enum EXP_TYPE {
Vielleicht gleich einen aussagekräftigeren Name. CombatExpType. Ebenfalls kein caps bei Enum Namen, nur bei den Werten

2018-08-10 21:23 UTC, jsprey commented on src/main/java/mastery/eventhandlers/husbandry/HusbandryUtils.java
> +    static boolean isShearable(Entity target, Item item) {
Mal prüfen wie wir die Methoden in den andern Utils Klassen gemacht haben. Also vom Zugriffsmodifier

2018-08-10 21:23 UTC, jsprey commented on src/main/java/mastery/capability/skillclasses/CombatMastery.java
> -    public enum EXP_TYPE {
nvm hast du ja entfernt 🗡

2018-08-10 21:23 UTC, jsprey commented on src/main/java/mastery/eventhandlers/husbandry/HusbandryExperience.java
> +    public void useItemEven(PlayerInteractEvent.EntityInteract event) {
useItemEven: Soll das Even oder Event sein? Vielleicht Event weglassen und nur useItem

2018-08-11 11:04 UTC, Ixsen commented on src/main/java/mastery/eventhandlers/husbandry/HusbandryUtils.java
> +    static boolean isShearable(Entity target, Item item) {
Hab alle gepackageprivated

2018-08-11 11:04 UTC, Ixsen commented on src/main/java/mastery/eventhandlers/husbandry/HusbandryExperience.java
> +    public void useItemEven(PlayerInteractEvent.EntityInteract event) {
Sollte event heißen, braucht aber wirklich nicht sein ^^

2018-08-11 11:59 UTC, merged