Fixed exp for mining and added tnt-mining
Ixsen/Mastery pull request #18
Opened 2018-08-11 19:51 UTC by Ixsen

2018-08-11 19:52 UTC, Ixsen commented on src/main/java/mastery/eventhandlers/AbstractExperienceHandler.java
> -    		return;
Du hast teilweise immer noch tabs bei der Formatierung da, nochmal nachcheckern

2018-08-12 06:55 UTC, jsprey requested changes
Nochmal absprechen

2018-08-12 06:55 UTC, Subaro commented on src/main/java/mastery/eventhandlers/mining/MiningUtils.java
> +        return Minecraft.getMinecraft().world.getBlockState(pos).getBlock();
Wie sieht das aus wenn man was im Nether abbaut? Nimmt der mit getMinecraft() immer die Welt des jeweiligen Spielers und nicht einfach die normale Welt? Auf jeden Fall nochmal checken

2018-08-12 06:55 UTC, Subaro commented on src/main/java/mastery/eventhandlers/mining/MiningUtils.java
> +        if (block instanceof BlockOre || block == Blocks.REDSTONE_ORE && !hasSilkTouch) {
Ist REDSTONE_ORE kein BlockOre?

2018-08-12 06:55 UTC, Subaro commented on src/main/java/mastery/eventhandlers/mining/MiningExperience.java
> +                    MiningUtils.hasSilkTouchEnchantedTool(breakEvent.getPlayer())));
Wir sollten hier jeden Block mit einem boolean taggen, dass dieser abgebaut wurde. Es gibt also nur beim 1 mal exp ;)

2018-08-12 15:23 UTC, Ixsen commented on src/main/java/mastery/eventhandlers/mining/MiningUtils.java
> +        if (block instanceof BlockOre || block == Blocks.REDSTONE_ORE && !hasSilkTouch) {
Leider nicht, Klammern angepasst

2018-08-12 15:23 UTC, Ixsen commented on src/main/java/mastery/eventhandlers/mining/MiningExperience.java
> +                    MiningUtils.hasSilkTouchEnchantedTool(breakEvent.getPlayer())));
Wird in neuer Story gemacht ^^

2018-08-12 15:24 UTC, Ixsen commented on src/main/java/mastery/eventhandlers/mining/MiningUtils.java
> +        return Minecraft.getMinecraft().world.getBlockState(pos).getBlock();
Funktioniert ^^

2018-08-12 15:48 UTC, merged