++added up popup utils class to inform the user about something
Ixsen/Mastery pull request #23
Opened 2018-08-15 19:59 UTC by Subaro

++added effects for crafting

2018-08-15 20:54 UTC, Ixsen requested changes

2018-08-15 20:54 UTC, Ixsen commented on src/main/java/mastery/ui/utils/UIPopupUtils.java
> +        Minecraft.getMinecraft().player.sendStatusMessage(new TextComponentString(message), true);
Hatte keine Zeit das zu testen, bin mir aber ziemlich sicher, dass das nen Nullpointer auf einem Server verursacht. Siehe oben, da wird Server only gesichert.  Man sollte der Methode @SideOnly(Side.CLIENT) spendieren und das Event anpassen, sodass das bei Trennung auch funktioniert. Trennung von Client und Server sollten wir sowieso mal Testen

2018-08-15 20:54 UTC, Ixsen commented on src/main/java/mastery/eventhandlers/crafting/CraftingEffects.java
> +        if (event.player != null && !event.player.getEntityWorld().isRemote) {
Hier sagst du Server only

2018-08-15 20:54 UTC, Ixsen commented on src/main/java/mastery/ui/utils/UIPopupUtils.java
> +        player.sendStatusMessage(new TextComponentString(message), true);
Würde das vom Server aus funktionieren?

2018-08-16 16:05 UTC, Subaro commented on src/main/java/mastery/eventhandlers/crafting/CraftingEffects.java
> +        if (event.player != null && !event.player.getEntityWorld().isRemote) {
Jo ist ja auch richtig  so

2018-08-16 16:05 UTC, Subaro commented on src/main/java/mastery/ui/utils/UIPopupUtils.java
> +        player.sendStatusMessage(new TextComponentString(message), true);
Ja tut es

2018-08-16 20:45 UTC, Ixsen approved these changes

2018-08-16 20:45 UTC, merged